### PR TITLE
config: compile NT36672C as a module because sweet does not have it

### PR DESCRIPTION
**Pull request by Etn40ff**
Signed-off-by: Salvatore Stella <salvatore.stella@univaq.it>

### CODE REVIEW

**Comment by Etn40ff** [comment]
Please wait: this pull request is not ready yet

**Comment by Etn40ff** [comment]
I might need some help here.

sweet has a different touchscreen than surya. Currently my kernel complains about it:

```[NVT-ts] nvt_driver_init 2490: Unknown Touch```

I thought that a simple fix would be to set `CONFIG_TOUCHSCREEN_NT36672C_HOSTDL_SPI=m` but make is unhappy about it:

```
...
ERROR: modpost: missing MODULE_LICENSE() in drivers/input/touchscreen/nt36672c/nt36xxx_fw_update.o
ERROR: modpost: missing MODULE_LICENSE() in drivers/input/touchscreen/nt36672c/nt36xxx_ext_proc.o
ERROR: modpost: "irq_to_desc" [drivers/input/touchscreen/nt36672c/nt36xxx.ko] undefined!
ERROR: modpost: "nvt_extra_proc_deinit" [drivers/input/touchscreen/nt36672c/nt36xxx.ko] undefined!
ERROR: modpost: "Boot_Update_Firmware" [drivers/input/touchscreen/nt36672c/nt36xxx.ko] undefined!
ERROR: modpost: "nvt_extra_proc_init" [drivers/input/touchscreen/nt36672c/nt36xxx.ko] undefined!
ERROR: modpost: "nvt_update_firmware" [drivers/input/touchscreen/nt36672c/nt36xxx.ko] undefined!
ERROR: modpost: "saved_command_line" [drivers/input/touchscreen/nt36672c/nt36xxx.ko] undefined!
ERROR: modpost: "ts" [drivers/input/touchscreen/nt36672c/nt36xxx_fw_update.ko] undefined!
ERROR: modpost: "nvt_set_page" [drivers/input/touchscreen/nt36672c/nt36xxx_fw_update.ko] undefined!
ERROR: modpost: "CTP_SPI_WRITE" [drivers/input/touchscreen/nt36672c/nt36xxx_fw_update.ko] undefined!
ERROR: modpost: "nvt_bootloader_reset" [drivers/input/touchscreen/nt36672c/nt36xxx_fw_update.ko] undefined!
WARNING: modpost: suppressed 15 unresolved symbol warnings because there were too many)
...
```

**Comment by Anax-M** [comment]
Maybe using an completely other driver?
I read something Here and there and saw that the Poco F3 uses an completely other display, And i found an Linux Driver for gtx8, maybe someone can port it for sweet? (I dont really know much about drivers, so it could be that this is already the driver but i couldnt See something that leads to this driver or sound like it)

Found [that driver that could work](https://github.com/goodix/gtx8_driver_linux) 

[What i read about the drivers](https://www.deviceinfohw.ru/devices/index.php?page=1&platform=&cpu=&brand=&filter=&submit=&Last%20uploads=)

Maybe i helped Here a bit

**Comment by 99degree** [comment]
just in case you are interested in regmap spi input touch screen driver, you may find my below driver useful.

https://github.com/99degree/linux/commit/405f5204bdebf64ec34cc2bf2cc5904e6ba2de51
https://github.com/99degree/linux/commit/b0c71eff73d3ff954c3b3f3ddd8a343de8f4cbe8

**Comment by JIaxyga** [comment]
> just in case you are interested in regmap spi input touch screen driver, you may find my below driver useful.
> 
> [99degree@405f520](https://github.com/99degree/linux/commit/405f5204bdebf64ec34cc2bf2cc5904e6ba2de51) [99degree@b0c71ef](https://github.com/99degree/linux/commit/b0c71eff73d3ff954c3b3f3ddd8a343de8f4cbe8)

Where can I contact you? Can you write to me at my email danila@jiaxyga.com or telegram @jiaxyga or matrix @jiaxyga:matrix.org?

**Comment by JIaxyga** [comment]
Thanks!

Will be switched to module after merging the new driver into the main branch for pmaports.

So close this PR

**Pull request closed without merging**
