### PR TITLE
drm: panel: huaxing-nt36672c: Add DSC support

### PR DESCRIPTION
**Pull request by ywmaa**

### CODE REVIEW

**Comment by JIaxyga** [comment]
Test branch removed. PR closed automatically

**Comment by JIaxyga** [comment]
Also main branch should not contain commits that do not actually work or break working features

**Comment by ywmaa** [comment]
yeah no problem, this looks like it is going to take sometime from me anyway.

**Comment by MarijnS95** [comment]
See also #15, this needs quite a bit more effort @ywmaa :wink:

**Comment by ywmaa** [comment]
> See also #15, this needs quite a bit more effort @ywmaa wink

I will try, I am very new to linux kernel dev.

**Comment by MarijnS95** [comment]
I have since accumulated _even more_ DSC fixes, but most (perhaps all?) are not applicable to videomode panels. They haven't solved anything for our commandmode panels yet though, but I can link and share them if it doesn't work yet.

**Pull request closed without merging**
